"use client";
import { Inter } from "next/font/google";
import "../app/assets/css/globals.css";
import Sidebar from "./components/Sidebar";
import FooterC from "./components/FooterC";
import MobileNavC from "./components/MobileNav";
import MobileContactUsC from "./components/MobileContactUsC";
const inter = Inter({ subsets: ["latin"] });
import React from "react";

import { appWithTranslation } from "next-i18next";
import { LanguageProvider } from "../app/hooks/LanguageContext";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function RootLayout({ children }) {
  return (
    <html lang="ru">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>NDD | webstudio</title>
        <link rel="icon" href="webstudio_logo.jpg" type="image/x-icon"></link>
      </head>
      <body className={inter.className}>
        <LanguageProvider>
          <MobileContactUsC></MobileContactUsC>
          <MobileNavC></MobileNavC>

          <Sidebar></Sidebar>
          {children}
          <div id="wrapper">
            <FooterC></FooterC>
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}

export default appWithTranslation(RootLayout);
